version: '3.8'

services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - family-network

  backend:
    build: ./server
    env_file: .env
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - family-network

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - family-network

volumes:
  pg_data:

networks:
  family-network:
    driver: bridge
